Remove references to Runner
CenturyLinkCloud/PublicKB pull request #3444
Opened 2021-11-03 18:40 UTC by jeremypeters49

Runner was deprecated in 2020 and is no longer available.

2021-11-03 18:41 UTC, ldsz89 requested changes

2021-11-03 18:41 UTC, ldsz89 commented on Control Portal/control-portal-navigation-update.md
> -
Please do not remove this section. Please update with your information and the most recent date of change.

2021-11-03 20:51 UTC, jeremypeters49 commented
Date section re-added and updated.

2021-11-04 13:13 UTC, ldsz89 approved these changes

2021-11-04 13:13 UTC, merged